parameters:

    geolocation:
        locator_factory:
            class:              Meup\Bundle\GeoLocationBundle\Domain\Handler\LocatorFactory
        distance_calculator_factory:
            class:              Meup\Bundle\GeoLocationBundle\Domain\Handler\DistanceCalculatorFactory
        services:
            google:
                api_key:        API_KEY
                endpoint:       https://maps.googleapis.com/maps/api/geocode/json
                locator_class:  Meup\Bundle\GeoLocationBundle\Domain\Handler\Google\Locator
            bing:
                api_key:        API_KEY
                endpoint:       http://dev.virtualearth.net/REST/v1/Locations?countryRegion=countryRegion&adminDistrict=adminDistrict&locality=locality&postalCode=postalCode&addressLine=addressLine&userLocation=userLocation&userIp=userIp&usermapView=usermapView&includeNeighborhood=includeNeighborhood&maxResults=maxResults&key=BingMapsKey
                locator_class:  Meup\Bundle\GeoLocationBundle\Domain\Handler\Bing\Locator
        service: google

services:

    meup_geolocation.locator_factory:
        class:
        arguments: 
            - %geolocation.services%

    meup_geolocation.distance_calculator_factory:
        class:
        arguments:
            - %geolocation.services%

    meup_geolocation.locator:
        class:           Meup\Bundle\GeoLocationBundle\Domain\Handler\LocatorInterface
        factory_service: meup_geolocation.locator_factory
        factory_method:  create
        arguments: 
            - %geolocation.service%

    meup_geolocation.distance_calculator:
        class:           Meup\Bundle\GeoLocationBundle\Domain\Handler\DistanceCalculatorInterface
        factory_service: meup_geolocation.distance_calculator_factory
        factory_method:  create
        arguments:
            - %geolocation.service%
