parameters:

services:

    meup_geolocation.http_client:
        class: GuzzleHttp\Client
#
#
#    meup_geolocation.locator:
#        class:
#        arguments: []

    meup_geolocation.google_locator:
        class: Meup\Bundle\GeoLocationBundle\Provider\Google\Locator
        arguments: 
            - @meup_geolocation.http_client
            - %google_api_key%
        tags:
            - { name: meup_geolocation.locator }
